# Generated by Django 5.0.3 on 2025-07-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sheet_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
